apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
              name: redis
        - name: rediscontainer
          image: rediscommander/redis-commander
          ports:
            - containerPort: 8081
              name: redis
